CARDS = (
    '2 Clubs',
    '3 Clubs',
    '4 Clubs',
    '5 Clubs',
    '6 Clubs',
    '7 Clubs',
    '8 Clubs',
    '9 Clubs',
    '10 Clubs',
    'Jack of Clubs',
    'Queen of Clubs',
    'King of Clubs',
    'Ace of Clubs',
    '2 Diamonds',
    '3 Diamonds',
    '4 Diamonds',
    '5 Diamonds',
    '6 Diamonds',
    '7 Diamonds',
    '8 Diamonds',
    '9 Diamonds',
    '10 Diamonds',
    'Jack of Diamonds',
    'Queen of Diamonds',
    'King of Diamonds',
    'Ace of Diamonds',
    '2 Hearts',
    '3 Hearts',
    '4 Hearts',
    '5 Hearts',
    '6 Hearts',
    '7 Hearts',
    '8 Hearts',
    '9 Hearts',
    '10 Hearts',
    'Jack of Hearts',
    'Queen of Hearts',
    'King of Hearts',
    'Ace of Hearts',
    '2 Spades',
    '3 Spades',
    '4 Spades',
    '5 Spades',
    '6 Spades',
    '7 Spades',
    '8 Spades',
    '9 Spades',
    '10 Spades',
    'Jack of Spades',
    'Queen of Spades',
    'King of Spades',
    'Ace of Spades'
)
